import { Providers } from "./providers";
import { fonts } from "./fonts";
import SiteOuterLayout from "@/layouts/SiteOuterLayout";
import { MaxWidthContainerLayout } from "@/layouts/MaxWidthContainerLayout";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${fonts.barlow.variable} ${fonts.poppins.variable}`}>
      <body>
        <Providers>
          <SiteOuterLayout>
            <MaxWidthContainerLayout>{children}</MaxWidthContainerLayout>
          </SiteOuterLayout>
        </Providers>
      </body>
    </html>
  );
}
